version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOST=0.0.0.0
      - PLAYWRIGHT_SERVICE_URL=http://playwright:3000
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - FIRECRAWL_API_URL=${FIRECRAWL_API_URL}
      - GUPY_BUILD_ID=${GUPY_BUILD_ID}
    depends_on:
      - playwright

  playwright:
    build:
      context: .
      dockerfile: playwright.Dockerfile
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    shm_size: '2gb' 